#ifndef BUTTON_CONFIG_H_
#define BUTTON_CONFIG_H_

#define BUTTON_IO_NUM 4
#define BUTTON_ACTIVE_LEVEL 0

#define BUTTON_LONG_PRESS_TIME 1000
#define BUTTON_SHORT_PRESS_TIME 200

#endif /* BUTTON_CONFIG_H_ */
